### ISSUE TITLE
Feature Request: Maint.Mode for MonitoringObject (Class)

### ISSUE THREAD

**Issue by s2patrick** [ehrnst/System-Center-Operations-Manager-API#1]
Hi,
great API, thanks for that.

It would be great to see the method to set a Maint. Mode not just for Windows Computers, but for any class. For instance, we need to set MM for a class to which service monitors are targeted, not the whole machine.

Thanks again and best,
Patrick

**Comment by ehrnst** [comment]
Hi Partick, thank you for your feedback.

Just to be clear, you want to maintenance a monitoring object regardless of class, right? If that is the case I think I can manage that, i just have to find the time to implement it.

**Comment by s2patrick** [comment]
Hi,
yes... that is correct.
/patrick

**Comment by ehrnst** [comment]
Patrick. I will find some time to review this, but if you add this to the maintenance controller i believe it should work.
`        /// <summary>
        /// Puts the specified monitoring object in maintenance mode.
        /// </summary>
        /// <param name="Data">Json string with Id, # of minutes and a comment</param>
        /// <example>
        /// {
        ///     "id": "Guid",
        ///     "Minutes": 10,
        ///     "comment": "doing maintenance"
        /// }
        /// </example>
        /// <response code="201">Successfully added maintenance mode for the object</response>
        /// <response code="400">Bad request. Check json input</response>
        /// <response code="409">Conflict: object already in maintenance</response>
        [HttpPost]
        [Route("API/ObjectMaintenance")]
        public IHttpActionResult EnableObjectMaintenance(SCOMObjectMaintenanceModel Data)
        {
            //create a Guid from the json input
            var ObjectId = new Guid(Data.id);
            //get the monitoring object by Guid
            var monObject = mg.EntityObjects.GetObject<MonitoringObject>(ObjectId, ObjectQueryOptions.Default);

            List<SCOMMonitoringObjectModel> MonitoringObjects = new List<SCOMMonitoringObjectModel>();

            List<SCOMObjectMaintenanceModel> MaintenanceObjects = new List<SCOMObjectMaintenanceModel>();

                if (!monObject.InMaintenanceMode)
                {
                    {
                        //set maintenance properties
                        DateTime startTime = DateTime.UtcNow;
                        DateTime schedEndTime = DateTime.UtcNow.AddMinutes(Data.Minutes);
                        MaintenanceModeReason reason = MaintenanceModeReason.PlannedOther;
                        string comment = Data.comment;

                        monObject.ScheduleMaintenanceMode(startTime, schedEndTime, reason, comment);

                        //Add properties to list
                        SCOMObjectMaintenanceModel maintenanceObject = new SCOMObjectMaintenanceModel();
                        maintenanceObject.displayName = monObject.DisplayName;
                        maintenanceObject.id = monObject.Id.ToString();
                        maintenanceObject.EndTime = schedEndTime;
                        maintenanceObject.Minutes = Data.Minutes;
                        maintenanceObject.comment = comment;

                        //add computers to list
                        MaintenanceObjects.Add(maintenanceObject);

                    }
                }

                //If computer already in maintenance. Do nothing and list info
                else
                {
                    MaintenanceWindow MaintenanceWindow = monObject.GetMaintenanceWindow();

                    HttpResponseMessage message = new HttpResponseMessage(HttpStatusCode.Conflict);
                    message.Content = new StringContent("Object already in maintenance until" + MaintenanceWindow.ScheduledEndTime);
                    throw new HttpResponseException(message);

                }

            //Return list of computers as Json
            return Json(MaintenanceObjects);

        }`

**Comment by ehrnst** [comment]
Patrick. Try the api from the dev branch. A lot of updates including the one you requested

**Comment by s2patrick** [comment]
Ehrnst, hi. Awesome, thank you for your time. Will try next week once I am back at my lab. I owe you a beer! :-)
