### ISSUE TITLE
Unable to get Performance data of server

### ISSUE THREAD

**Issue by HarishAP88** [ehrnst/System-Center-Operations-Manager-API#21]
I am facing the below issue while trying to get the performance data for windows servers.

Please help me to fix the issue
{
    "Message": "No HTTP resource was found that matches the request URI 'http://10.174.180.179/API/Perf/hourly/4b7c21f1-4870-6eb6-8d7d-384cd9b12769?counterName=Percent Memory Used'."
}

**Comment by ehrnst** [comment]
I believe the counter is 'PercentMemoryUsed' without blank spaces.
Please reopen if that's not the case

**Comment by HarishAP88** [comment]
Hi Ehrnst
I have tried without spaces as well still same error.
 
 "Message": "No HTTP resource was found that matches the request URI 'http://10.174.180.179/API/Perf/hourly/8a83570f-1ea0-0fd0-d9d7-7474d886b05e?counterName=PercentMemoryUsed&startDate=2018-04-06 01:00:00.000&endDate=2018-04-07 01:00:00.000

**Comment by HarishAP88** [comment]
Can u share me the document what all needs to be enabled on SCOM and DW server so that i will try it once.

I am able to get Alerts .Computers and Objects . Only for Perf i am getting the above Error.

**Comment by ehrnst** [comment]
Sorry for my very late response. You are sure that your Id is correct? 
If the user has access to read dB and delegation us in place this should work  (assuming different dw server from api)

**Comment by HarishAP88** [comment]
user has full access to data base . i have enabled delegation in 
![delegation to db server](https://user-images.githubusercontent.com/38213850/39050036-6c03b4dc-44c1-11e8-99a4-d96116212b3c.PNG)
AD.

**Comment by ehrnst** [comment]
I am terribly sorry for not responding here. I assume delegation works unconstrained with out issues.
Can you confirm the manged entity is correct by using the windows computer endpoint with computername to retrieve the ID, and use it at the performance endpoints?

**Comment by HarishAP88** [comment]
HI Ehrnst

I have passed the ID of the computer in the managed entity still facing the same issue. I have attached the screenshot of computer ID.

http://10.134.180.179/API/Perf/5784e71b-fec4-055e-0b2f-052c6757bb01?counterName=PercentMemoryUsed&startDate=2018-04-06 01:00:00.000&endDate=2018-04-07 01:00:00.000
![postman](https://user-images.githubusercontent.com/38213850/39853043-800edf48-543d-11e8-84a6-dc5ee7899a3c.PNG)

![computerid](https://user-images.githubusercontent.com/38213850/39852972-2086c9a0-543d-11e8-9f19-148123759550.PNG)

**Comment by ehrnst** [comment]
This is very strange. Are you using the latest version? Is the same thing happening with the hourly/daily? just tried my self
https://url/API/Perf/2f164b6c-b972-025a-47d5-8c1cc249b27b?counterName=PercentMemoryUsed&startDate=2018-01-15T02%3A00%3A00&endDate=2018-05-16T02%3A00%3A00

**Comment by HarishAP88** [comment]
Yes .. I am using the latest version and also tried old version as well but facing the same issue for perf controller for all hourly/daily/monthly..

Can u check and provide the solution ..

**Comment by HarishAP88** [comment]
Are u facing the same issue ??

**Comment by ehrnst** [comment]
No, I'm not, but I will try to install a new instance and check that.

**Comment by ehrnst** [comment]
I cannot reproduce this. Anyone else who experience this issue, please chime in.
Just to be clear, you have the same issue if you don't specify start/end date, right? What does swagger say?

**Comment by HarishAP88** [comment]
I am using postman and didn'ttry without startdate adnd enddate.. Let me try once

**Comment by HarishAP88** [comment]
Hi Ehrnst,

i found the below while testing in postman 

System.Data.SqlClient.SqlException (0x80131904): Cannot open database "OperationsManagerDW" requested by the login. The login failed.

In my env , DW databasename is OperationsManager_ADAPTORDW and i have updated the same in SCOMPerfcontroller.cs file but didnt work amd still it is pointing to OperationsManagerDW database.

Please suggest me where to change it to make it work.

**Comment by ehrnst** [comment]
Hi,

Of course. I should have taken that in to consideration. Many use different db names. I don't remember putting db config in any other places than that controller and the servername you can set in web.config.

**Comment by HarishAP88** [comment]
Thanks Ehrnst. Wen can we get latest API.

As of now i have made the changes in the SCOMperfcontroller.cs and tested it in scom 2012 , its working fine and giving the proper data.

Also when i am trying to test the same in SCOM 2016 instance , it is giving null output ([] )and not throwing any error. I have made the same changes which i have done for 2012 but When i execute the SQl query , it has data for that server.

**Comment by ehrnst** [comment]
Unfortunately, I don't have any spare time in the coming months to make the dB name configurable.
When it comes to 2016 we use that in all our environments, without issues
