### ISSUE TITLE
"An error has occured"

### ISSUE THREAD

**Issue by d4rk0de** [ehrnst/System-Center-Operations-Manager-API#24]
Hi

This looks amazing and I wanted to try it, but I cannot find the reason why I get this error:

```
Response Body
{
  "Message": "An error has occurred."
}
Response Code
500
Response Headers
{
  "persistent-auth": "true",
  "pragma": "no-cache",
  "date": "Thu, 06 Sep 2018 15:47:46 GMT",
  "server": "Microsoft-IIS/8.5",
  "x-aspnet-version": "4.0.30319",
  "x-powered-by": "ASP.NET",
  "content-type": "application/json; charset=utf-8",
  "cache-control": "no-cache",
  "content-length": "36",
  "expires": "-1"
}
```

I've set the servers in the web config file, I've added the delegation, the impersonation works because I tried to run the same powershell command without using the default credentials and I get access denied.

Any help would be much appreciated.

Thanks

**Comment by ehrnst** [comment]
Hi. On what endpoint is this? Have you tried the same endpoint through
swagger? Yourapiurl /swagger

Martin

**Comment by d4rk0de** [comment]
Sorry, ignore for the moment. There were some permissions issues on the account I was logged on I think. Just excited using it :)
