### ISSUE TITLE
When calling API from powershell getting an error at random times

### ISSUE THREAD

**Issue by Saro27** [ehrnst/System-Center-Operations-Manager-API#26]
Hello,

I need help in getting this fixed. I am calling the API through PS and random times I get the error message as when I run with schedule "{"Message: An error Has occured"}. to fix this if I run with immediate I get this fixed. can you help me how to fix this for the intermittent issue with Schedule option.

**Comment by ehrnst** [comment]
Hi, i havent seen this issue. Do you have an example query?
