### ISSUE TITLE
Inquiry on any available endpoint for removing a computer from maintenance mode

### ISSUE THREAD

**Issue by eapesa** [ehrnst/System-Center-Operations-Manager-API#29]
Hi Martin,

I would just like to ask if there's a counterpart endpoint for removing a computer from maintenance mode? Thanks to your APIs we were able to automate stuff in SCOM, there are times though that we make mistakes in putting a computer to maintenance mode and it would be helpful if we have an endpoint to use for this as well however I am not sure if I overlooked your list of APIs and missed one dedicated for this.

Thank you!

Regards,
Elixa

**Comment by ehrnst** [comment]
Hi Elixa thanks for reaching out. I'm glad you find the API useful! To be honest, I haven't touched the code or used the API my self for about two years. Although I remember looking into this, and by using the same endpoint you should be able to use a parameter to end existing maintenance mode. https://github.com/ehrnst/System-Center-Operations-Manager-API/blob/master/SCOM%20API/Controllers/SCOMMaintenanceController.cs

https://github.com/ehrnst/System-Center-Operations-Manager-API/issues/9 if you look at this issue, I have done some work that is somewhat implemented in master. Not sure what is missing. To be honest, I haven't used or looked at the code for two years. 

Please check what you have available :)

**Comment by ehrnst** [comment]
Closing. Looking to solve this with issue https://github.com/ehrnst/System-Center-Operations-Manager-API/issues/9

**Comment by eapesa** [comment]
This is great Martin! I haven't noticed that there are maintenance endpoints as I was fixated to the Alerts endpoint. Thanks, we'll try this out.
