### ISSUE TITLE
Hello, we are get some error for this api, you can help me ?

### ISSUE THREAD

**Issue by lyerA19** [ehrnst/System-Center-Operations-Manager-API#31]
Hi,

We are found some error, we need some help, thanks!
What's the param classId from or How to get the all monitoringObject? [GET]   API/MonitoringObject/class/{classId}

What's the param for managedEntityId from api?[GET]   API/Perf/{managedEntityId}

What's wrong with result message '{"Message":"An   error has occurred."}' [GET]   API/Computer/Linux

This return message 'IIS 返回 405 - 不允许用于访问此页的   HTTP 谓词。'  [PUT]   API/Alerts/{id}

Best regards,
Chen

**Comment by ehrnst** [comment]
Hi Chen. See my answers below;

> What's the param classId from or How to get the all monitoringObject? [GET] API/MonitoringObject/class/{classId}
You will need the class id for example using `Get-ScomClass` in PowerShell

> 
> What's the param for managedEntityId from api?[GET] API/Perf/{managedEntityId}
you will pass in the monitoringObject/managedEntityId, perf counter, and date
> 
> What's wrong with result message '{"Message":"An error has occurred."}' [GET] API/Computer/Linux
> 
> This return message 'IIS 返回 405 - 不允许用于访问此页的 HTTP 谓词。' [PUT] API/Alerts/{id}
> 
Sorry, but my Chinese is limited :)
> Best regards,
> Chen

You have your own swagger page to test all the endpoints as well.
https://adatum.no/operationsmanager/update-scom-web-api

Do be aware, I created this API 5 years ago, and I don't maintain it anymore.
