### ISSUE TITLE
No output from Alerts, only from MonitoringObject

### ISSUE THREAD

**Issue by Outek** [ehrnst/System-Center-Operations-Manager-API#6]
Hi, thank you for the API

I have some troubles to get alerts from the api

with MonitoringObject everything looks good:
PS C:\Windows\system32> Invoke-restmethod -uri 'http://localhost:80/API/MonitoringObject/fb0854c9-1094-be55-327a-2598d5550baf' -Credential $cred

but with Alerts, nothing is echoed, neither with Computers
Invoke-RestMethod -Uri 'http://localhost:80/API/Alerts' -Credential $cred 

Maybe you can give me a little hint?

**Comment by ehrnst** [comment]
Hi. Strange. Have you tried using visual studio or just deployed the code?
Is swagger also failing? Are you using the version currently in the master
branch?

Martin Ehrnst

**Comment by Outek** [comment]
I tried it with the zip file from the master branch.
i didn't test it with swagger, but i'll try this.

**Comment by Outek** [comment]
Sorry for bothering you, it was an issue with the credentials/sdk account on scom itself.

**Comment by ehrnst** [comment]
Not a problem hope you will find it useful!
