### ISSUE TITLE
Feature Request: Get monitoring object(s) by DisplayName

### ISSUE THREAD

**Issue by s2patrick** [ehrnst/System-Center-Operations-Manager-API#7]
Hi Martin,
current version works well, thank you. 

Maybe it is possible at some point in time to add the possibility to get the properties of objects by searching for the DisplayName (instead of only GUID)?

Best regards,
Patrick

Again: many, many thanks for your time and your effort. (I really would contribute if I'd be better in dev (my skills end with PowerShell :-) ).

**Comment by ehrnst** [comment]
Hi Patrick. Great to hear you find the API useful. i understand your request, but i don't have the time to develop it atm. To get it to work, without creating too much load on the management server we would have to specify class along with the display name.

btw
this is my first CS project ;)

**Comment by s2patrick** [comment]
Hey,
yeah... class might make sense, probably optional. 

I understand that this takes time - so: no worries. I'll try by my own once I am back in the office, maybe I am able to contribute.

Best,
Patrick

**Comment by ehrnst** [comment]
Hi, if it helps, the version in dev now supports getting all monitoring objects based on a class (supply class id)
the endpoint returns only basic properties and is pretty fast 👍
